apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-example-ingres
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: flask-app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-example
            port:
              number: 8000
